name: Linting, testing, building
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
      - name: linting css
        run: npm run lint:styles
      - name: unit testing
        run: npm run unit
      - name: e2e testing
        run: npm run wdio