name: Linting, testing, building
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build
      - name: linting by eslint
        run: npm run lint:eslint
      - name: linting typescript
        run: npm run lint:ts
      - name: linting styles
        run: npm run lint:styles
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run build-storybook
      - name: ui testing
        run: npm run chromatic
#      - name: e2e testing
#        run: npm run test:e2e